#!/bin/bash
#
# PipeOps GCP Credentials Setup Script
# Creates a service account with the permissions required to provision
# and manage GKE clusters, networking, storage, and artifact registry.
#
# Usage:
#   ./create_credentials_gcp.sh <project_id> <role_name> <service_account_name>
#
# Example:
#   ./create_credentials_gcp.sh my-gcp-project pipeops-role pipeops-sa
#
# Prerequisites:
#   - gcloud CLI installed and authenticated (gcloud auth login)
#   - Owner or IAM Admin role on the target project
#   - jq installed

set -euo pipefail

# --- Argument validation -----------------------------------------------
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <project_id> <role_name> <service_account_name>"
    echo "  <project_id>:            GCP project to create resources in"
    echo "  <role_name>:             Custom IAM role name for PipeOps"
    echo "  <service_account_name>:  Service account name for PipeOps"
    exit 1
fi

project_name="$1"
role_name="$2"
service_account_name="$3"

# --- Pre-flight checks -------------------------------------------------
for cmd in gcloud jq; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "Error: '$cmd' is required but not installed." >&2
        exit 1
    fi
done

if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" 2>/dev/null | grep -q .; then
    echo "Error: No active gcloud authentication. Run 'gcloud auth login' first." >&2
    exit 1
fi

# --- Enable required APIs ---------------------------------------------
echo "Activating required GCP APIs..."
apis=(
    container.googleapis.com
    compute.googleapis.com
    artifactregistry.googleapis.com
    storage.googleapis.com
    cloudresourcemanager.googleapis.com
    run.googleapis.com
)
for api in "${apis[@]}"; do
    if ! gcloud services enable "$api" --project="$project_name" --quiet 2>/dev/null; then
        echo "Warning: Failed to enable $api — you may need to enable it manually." >&2
    fi
done
echo "APIs activated."

# --- Helper -------------------------------------------------------------
concat_permissions() {
    local IFS=','
    echo "$*"
}

# --- Permissions ---------------------------------------------------------
permissions=(
    # IAM
    "iam.serviceAccounts.create"
    "iam.serviceAccounts.delete"
    "iam.serviceAccounts.disable"
    "iam.serviceAccounts.enable"
    "iam.serviceAccounts.get"
    "iam.serviceAccounts.getIamPolicy"
    "iam.serviceAccounts.list"
    "iam.serviceAccounts.setIamPolicy"
    "iam.serviceAccounts.undelete"
    "iam.serviceAccounts.update"
    "iam.serviceAccounts.actAs"

    # Resource Manager
    "resourcemanager.projects.get"
    "resourcemanager.projects.setIamPolicy"
    "resourcemanager.projects.getIamPolicy"

    # -------------------------------------------------------------------
    # GKE / Kubernetes Engine (comprehensive)
    # -------------------------------------------------------------------
    "container.apiServices.create"
    "container.apiServices.delete"
    "container.apiServices.get"
    "container.apiServices.getStatus"
    "container.apiServices.list"
    "container.apiServices.update"
    "container.apiServices.updateStatus"
    "container.auditSinks.create"
    "container.auditSinks.delete"
    "container.auditSinks.get"
    "container.auditSinks.list"
    "container.auditSinks.update"
    "container.backendConfigs.create"
    "container.backendConfigs.delete"
    "container.backendConfigs.get"
    "container.backendConfigs.list"
    "container.backendConfigs.update"
    "container.bindings.create"
    "container.certificateSigningRequests.approve"
    "container.certificateSigningRequests.create"
    "container.certificateSigningRequests.delete"
    "container.certificateSigningRequests.get"
    "container.certificateSigningRequests.getStatus"
    "container.certificateSigningRequests.list"
    "container.certificateSigningRequests.update"
    "container.certificateSigningRequests.updateStatus"
    "container.clusterRoleBindings.create"
    "container.clusterRoleBindings.delete"
    "container.clusterRoleBindings.get"
    "container.clusterRoleBindings.list"
    "container.clusterRoleBindings.update"
    "container.clusterRoles.bind"
    "container.clusterRoles.create"
    "container.clusterRoles.delete"
    "container.clusterRoles.escalate"
    "container.clusterRoles.get"
    "container.clusterRoles.list"
    "container.clusterRoles.update"
    "container.clusters.connect"
    "container.clusters.create"
    "container.clusters.createTagBinding"
    "container.clusters.delete"
    "container.clusters.deleteTagBinding"
    "container.clusters.get"
    "container.clusters.getCredentials"
    "container.clusters.list"
    "container.clusters.listEffectiveTags"
    "container.clusters.listTagBindings"
    "container.clusters.update"
    "container.componentStatuses.get"
    "container.componentStatuses.list"
    "container.configMaps.create"
    "container.configMaps.delete"
    "container.configMaps.get"
    "container.configMaps.list"
    "container.configMaps.update"
    "container.controllerRevisions.create"
    "container.controllerRevisions.delete"
    "container.controllerRevisions.get"
    "container.controllerRevisions.list"
    "container.controllerRevisions.update"
    "container.cronJobs.create"
    "container.cronJobs.delete"
    "container.cronJobs.get"
    "container.cronJobs.getStatus"
    "container.cronJobs.list"
    "container.cronJobs.update"
    "container.cronJobs.updateStatus"
    "container.csiDrivers.create"
    "container.csiDrivers.delete"
    "container.csiDrivers.get"
    "container.csiDrivers.list"
    "container.csiDrivers.update"
    "container.csiNodeInfos.create"
    "container.csiNodeInfos.delete"
    "container.csiNodeInfos.get"
    "container.csiNodeInfos.list"
    "container.csiNodeInfos.update"
    "container.csiNodes.create"
    "container.csiNodes.delete"
    "container.csiNodes.get"
    "container.csiNodes.list"
    "container.csiNodes.update"
    "container.customResourceDefinitions.create"
    "container.customResourceDefinitions.delete"
    "container.customResourceDefinitions.get"
    "container.customResourceDefinitions.getStatus"
    "container.customResourceDefinitions.list"
    "container.customResourceDefinitions.update"
    "container.customResourceDefinitions.updateStatus"
    "container.daemonSets.create"
    "container.daemonSets.delete"
    "container.daemonSets.get"
    "container.daemonSets.getStatus"
    "container.daemonSets.list"
    "container.daemonSets.update"
    "container.daemonSets.updateStatus"
    "container.deployments.create"
    "container.deployments.delete"
    "container.deployments.get"
    "container.deployments.getScale"
    "container.deployments.getStatus"
    "container.deployments.list"
    "container.deployments.rollback"
    "container.deployments.update"
    "container.deployments.updateScale"
    "container.deployments.updateStatus"
    "container.endpointSlices.create"
    "container.endpointSlices.delete"
    "container.endpointSlices.get"
    "container.endpointSlices.list"
    "container.endpointSlices.update"
    "container.endpoints.create"
    "container.endpoints.delete"
    "container.endpoints.get"
    "container.endpoints.list"
    "container.endpoints.update"
    "container.events.create"
    "container.events.delete"
    "container.events.get"
    "container.events.list"
    "container.events.update"
    "container.frontendConfigs.create"
    "container.frontendConfigs.delete"
    "container.frontendConfigs.get"
    "container.frontendConfigs.list"
    "container.frontendConfigs.update"
    "container.horizontalPodAutoscalers.create"
    "container.horizontalPodAutoscalers.delete"
    "container.horizontalPodAutoscalers.get"
    "container.horizontalPodAutoscalers.getStatus"
    "container.horizontalPodAutoscalers.list"
    "container.horizontalPodAutoscalers.update"
    "container.horizontalPodAutoscalers.updateStatus"
    "container.hostServiceAgent.use"
    "container.ingresses.create"
    "container.ingresses.delete"
    "container.ingresses.get"
    "container.ingresses.getStatus"
    "container.ingresses.list"
    "container.ingresses.update"
    "container.ingresses.updateStatus"
    "container.jobs.create"
    "container.jobs.delete"
    "container.jobs.get"
    "container.jobs.getStatus"
    "container.jobs.list"
    "container.jobs.update"
    "container.jobs.updateStatus"
    "container.leases.create"
    "container.leases.delete"
    "container.leases.get"
    "container.leases.list"
    "container.leases.update"
    "container.limitRanges.create"
    "container.limitRanges.delete"
    "container.limitRanges.get"
    "container.limitRanges.list"
    "container.limitRanges.update"
    "container.localSubjectAccessReviews.create"
    "container.managedCertificates.create"
    "container.managedCertificates.delete"
    "container.managedCertificates.get"
    "container.managedCertificates.list"
    "container.managedCertificates.update"
    "container.mutatingWebhookConfigurations.create"
    "container.mutatingWebhookConfigurations.delete"
    "container.mutatingWebhookConfigurations.get"
    "container.mutatingWebhookConfigurations.list"
    "container.mutatingWebhookConfigurations.update"
    "container.namespaces.create"
    "container.namespaces.delete"
    "container.namespaces.get"
    "container.namespaces.getStatus"
    "container.namespaces.list"
    "container.namespaces.update"
    "container.namespaces.updateStatus"
    "container.networkPolicies.create"
    "container.networkPolicies.delete"
    "container.networkPolicies.get"
    "container.networkPolicies.list"
    "container.networkPolicies.update"
    "container.nodes.create"
    "container.nodes.delete"
    "container.nodes.get"
    "container.nodes.getStatus"
    "container.nodes.list"
    "container.nodes.proxy"
    "container.nodes.update"
    "container.nodes.updateStatus"
    "container.operations.get"
    "container.operations.list"
    "container.persistentVolumeClaims.create"
    "container.persistentVolumeClaims.delete"
    "container.persistentVolumeClaims.get"
    "container.persistentVolumeClaims.getStatus"
    "container.persistentVolumeClaims.list"
    "container.persistentVolumeClaims.update"
    "container.persistentVolumeClaims.updateStatus"
    "container.persistentVolumes.create"
    "container.persistentVolumes.delete"
    "container.persistentVolumes.get"
    "container.persistentVolumes.getStatus"
    "container.persistentVolumes.list"
    "container.persistentVolumes.update"
    "container.persistentVolumes.updateStatus"
    "container.podDisruptionBudgets.create"
    "container.podDisruptionBudgets.delete"
    "container.podDisruptionBudgets.get"
    "container.podDisruptionBudgets.getStatus"
    "container.podDisruptionBudgets.list"
    "container.podDisruptionBudgets.update"
    "container.podDisruptionBudgets.updateStatus"
    "container.podSecurityPolicies.create"
    "container.podSecurityPolicies.delete"
    "container.podSecurityPolicies.get"
    "container.podSecurityPolicies.list"
    "container.podSecurityPolicies.update"
    "container.podTemplates.create"
    "container.podTemplates.delete"
    "container.podTemplates.get"
    "container.podTemplates.list"
    "container.podTemplates.update"
    "container.pods.attach"
    "container.pods.create"
    "container.pods.delete"
    "container.pods.evict"
    "container.pods.exec"
    "container.pods.get"
    "container.pods.getLogs"
    "container.pods.getStatus"
    "container.pods.list"
    "container.pods.portForward"
    "container.pods.proxy"
    "container.pods.update"
    "container.pods.updateStatus"
    "container.priorityClasses.create"
    "container.priorityClasses.delete"
    "container.priorityClasses.get"
    "container.priorityClasses.list"
    "container.priorityClasses.update"
    "container.replicaSets.create"
    "container.replicaSets.delete"
    "container.replicaSets.get"
    "container.replicaSets.getScale"
    "container.replicaSets.getStatus"
    "container.replicaSets.list"
    "container.replicaSets.update"
    "container.replicaSets.updateScale"
    "container.replicaSets.updateStatus"
    "container.replicationControllers.create"
    "container.replicationControllers.delete"
    "container.replicationControllers.get"
    "container.replicationControllers.getScale"
    "container.replicationControllers.getStatus"
    "container.replicationControllers.list"
    "container.replicationControllers.update"
    "container.replicationControllers.updateScale"
    "container.replicationControllers.updateStatus"
    "container.resourceQuotas.create"
    "container.resourceQuotas.delete"
    "container.resourceQuotas.get"
    "container.resourceQuotas.getStatus"
    "container.resourceQuotas.list"
    "container.resourceQuotas.update"
    "container.resourceQuotas.updateStatus"
    "container.roleBindings.create"
    "container.roleBindings.delete"
    "container.roleBindings.get"
    "container.roleBindings.list"
    "container.roleBindings.update"
    "container.roles.bind"
    "container.roles.create"
    "container.roles.delete"
    "container.roles.escalate"
    "container.roles.get"
    "container.roles.list"
    "container.roles.update"
    "container.runtimeClasses.create"
    "container.runtimeClasses.delete"
    "container.runtimeClasses.get"
    "container.runtimeClasses.list"
    "container.runtimeClasses.update"
    "container.secrets.create"
    "container.secrets.delete"
    "container.secrets.get"
    "container.secrets.list"
    "container.secrets.update"
    "container.selfSubjectAccessReviews.create"
    "container.selfSubjectRulesReviews.create"
    "container.serviceAccounts.create"
    "container.serviceAccounts.createToken"
    "container.serviceAccounts.delete"
    "container.serviceAccounts.get"
    "container.serviceAccounts.list"
    "container.serviceAccounts.update"
    "container.services.create"
    "container.services.delete"
    "container.services.get"
    "container.services.getStatus"
    "container.services.list"
    "container.services.proxy"
    "container.services.update"
    "container.services.updateStatus"
    "container.statefulSets.create"
    "container.statefulSets.delete"
    "container.statefulSets.get"
    "container.statefulSets.getScale"
    "container.statefulSets.getStatus"
    "container.statefulSets.list"
    "container.statefulSets.update"
    "container.statefulSets.updateScale"
    "container.statefulSets.updateStatus"
    "container.storageClasses.create"
    "container.storageClasses.delete"
    "container.storageClasses.get"
    "container.storageClasses.list"
    "container.storageClasses.update"
    "container.storageStates.create"
    "container.storageStates.delete"
    "container.storageStates.get"
    "container.storageStates.getStatus"
    "container.storageStates.list"
    "container.storageStates.update"
    "container.storageStates.updateStatus"
    "container.storageVersionMigrations.create"
    "container.storageVersionMigrations.delete"
    "container.storageVersionMigrations.get"
    "container.storageVersionMigrations.getStatus"
    "container.storageVersionMigrations.list"
    "container.storageVersionMigrations.update"
    "container.storageVersionMigrations.updateStatus"
    "container.subjectAccessReviews.create"
    "container.thirdPartyObjects.create"
    "container.thirdPartyObjects.delete"
    "container.thirdPartyObjects.get"
    "container.thirdPartyObjects.list"
    "container.thirdPartyObjects.update"
    "container.tokenReviews.create"
    "container.updateInfos.create"
    "container.updateInfos.delete"
    "container.updateInfos.get"
    "container.updateInfos.list"
    "container.updateInfos.update"
    "container.validatingWebhookConfigurations.create"
    "container.validatingWebhookConfigurations.delete"
    "container.validatingWebhookConfigurations.get"
    "container.validatingWebhookConfigurations.list"
    "container.validatingWebhookConfigurations.update"
    "container.volumeAttachments.create"
    "container.volumeAttachments.delete"
    "container.volumeAttachments.get"
    "container.volumeAttachments.getStatus"
    "container.volumeAttachments.list"
    "container.volumeAttachments.update"
    "container.volumeAttachments.updateStatus"
    "container.volumeSnapshotClasses.create"
    "container.volumeSnapshotClasses.delete"
    "container.volumeSnapshotClasses.get"
    "container.volumeSnapshotClasses.list"
    "container.volumeSnapshotClasses.update"
    "container.volumeSnapshotContents.create"
    "container.volumeSnapshotContents.delete"
    "container.volumeSnapshotContents.get"
    "container.volumeSnapshotContents.getStatus"
    "container.volumeSnapshotContents.list"
    "container.volumeSnapshotContents.update"
    "container.volumeSnapshotContents.updateStatus"
    "container.volumeSnapshots.create"
    "container.volumeSnapshots.delete"
    "container.volumeSnapshots.get"
    "container.volumeSnapshots.getStatus"
    "container.volumeSnapshots.list"
    "container.volumeSnapshots.update"
    "container.volumeSnapshots.updateStatus"

    # -------------------------------------------------------------------
    # Artifact Registry
    # -------------------------------------------------------------------
    "artifactregistry.dockerimages.get"
    "artifactregistry.dockerimages.list"
    "artifactregistry.locations.get"
    "artifactregistry.locations.list"
    "artifactregistry.repositories.create"
    "artifactregistry.repositories.createTagBinding"
    "artifactregistry.repositories.delete"
    "artifactregistry.repositories.deleteArtifacts"
    "artifactregistry.repositories.deleteTagBinding"
    "artifactregistry.repositories.downloadArtifacts"
    "artifactregistry.repositories.get"
    "artifactregistry.repositories.getIamPolicy"
    "artifactregistry.repositories.list"
    "artifactregistry.repositories.listEffectiveTags"
    "artifactregistry.repositories.listTagBindings"
    "artifactregistry.repositories.readViaVirtualRepository"
    "artifactregistry.repositories.setIamPolicy"
    "artifactregistry.repositories.update"
    "artifactregistry.repositories.uploadArtifacts"
    "artifactregistry.tags.create"
    "artifactregistry.tags.delete"
    "artifactregistry.tags.get"
    "artifactregistry.tags.list"
    "artifactregistry.tags.update"
    "artifactregistry.versions.delete"
    "artifactregistry.versions.get"
    "artifactregistry.versions.list"

    # -------------------------------------------------------------------
    # Compute — networking, routers, firewalls, addresses, zones
    # -------------------------------------------------------------------
    "compute.addresses.create"
    "compute.addresses.delete"
    "compute.addresses.get"
    "compute.addresses.list"
    "compute.addresses.use"
    "compute.firewalls.create"
    "compute.firewalls.delete"
    "compute.firewalls.get"
    "compute.firewalls.list"
    "compute.firewalls.update"
    "compute.instanceGroupManagers.get"
    "compute.instanceGroupManagers.list"
    "compute.instanceGroupManagers.listEffectiveTags"
    "compute.instanceGroupManagers.listTagBindings"
    "compute.instanceGroupManagers.update"
    "compute.instanceGroupManagers.use"
    "compute.instanceGroups.get"
    "compute.instanceGroups.list"
    "compute.instanceGroups.update"
    "compute.instanceGroups.use"
    "compute.networks.access"
    "compute.networks.create"
    "compute.networks.createTagBinding"
    "compute.networks.delete"
    "compute.networks.deleteTagBinding"
    "compute.networks.get"
    "compute.networks.getEffectiveFirewalls"
    "compute.networks.getRegionEffectiveFirewalls"
    "compute.networks.list"
    "compute.networks.listEffectiveTags"
    "compute.networks.listPeeringRoutes"
    "compute.networks.listTagBindings"
    "compute.networks.mirror"
    "compute.networks.setFirewallPolicy"
    "compute.networks.updatePeering"
    "compute.networks.updatePolicy"
    "compute.networks.use"
    "compute.networks.useExternalIp"
    "compute.regions.get"
    "compute.regions.list"
    "compute.routers.create"
    "compute.routers.delete"
    "compute.routers.deleteRoutePolicy"
    "compute.routers.get"
    "compute.routers.getRoutePolicy"
    "compute.routers.list"
    "compute.routers.listBgpRoutes"
    "compute.routers.listRoutePolicies"
    "compute.routers.update"
    "compute.routers.updateRoutePolicy"
    "compute.routers.use"
    "compute.routes.create"
    "compute.routes.createTagBinding"
    "compute.routes.delete"
    "compute.routes.deleteTagBinding"
    "compute.routes.get"
    "compute.routes.list"
    "compute.routes.listEffectiveTags"
    "compute.routes.listTagBindings"
    "compute.subnetworks.create"
    "compute.subnetworks.createTagBinding"
    "compute.subnetworks.delete"
    "compute.subnetworks.deleteTagBinding"
    "compute.subnetworks.expandIpCidrRange"
    "compute.subnetworks.get"
    "compute.subnetworks.getIamPolicy"
    "compute.subnetworks.list"
    "compute.subnetworks.listEffectiveTags"
    "compute.subnetworks.listTagBindings"
    "compute.subnetworks.mirror"
    "compute.subnetworks.setIamPolicy"
    "compute.subnetworks.setPrivateIpGoogleAccess"
    "compute.subnetworks.update"
    "compute.subnetworks.use"
    "compute.subnetworks.useExternalIp"
    "compute.zones.get"
    "compute.zones.list"

    # -------------------------------------------------------------------
    # Cloud Storage — Terraform state backend
    # -------------------------------------------------------------------
    "storage.bucketOperations.cancel"
    "storage.bucketOperations.get"
    "storage.bucketOperations.list"
    "storage.buckets.create"
    "storage.buckets.createTagBinding"
    "storage.buckets.delete"
    "storage.buckets.deleteTagBinding"
    "storage.buckets.enableObjectRetention"
    "storage.buckets.get"
    "storage.buckets.getIamPolicy"
    "storage.buckets.getObjectInsights"
    "storage.buckets.list"
    "storage.buckets.listEffectiveTags"
    "storage.buckets.listTagBindings"
    "storage.buckets.restore"
    "storage.buckets.setIamPolicy"
    "storage.buckets.update"
    "storage.managedFolders.create"
    "storage.managedFolders.delete"
    "storage.managedFolders.get"
    "storage.managedFolders.getIamPolicy"
    "storage.managedFolders.list"
    "storage.managedFolders.setIamPolicy"
    "storage.multipartUploads.abort"
    "storage.multipartUploads.create"
    "storage.multipartUploads.list"
    "storage.multipartUploads.listParts"
    "storage.objects.create"
    "storage.objects.delete"
    "storage.objects.get"
    "storage.objects.getIamPolicy"
    "storage.objects.list"
    "storage.objects.overrideUnlockedRetention"
    "storage.objects.restore"
    "storage.objects.setIamPolicy"
    "storage.objects.setRetention"
    "storage.objects.update"

    # -------------------------------------------------------------------
    # Cloud Run
    # -------------------------------------------------------------------
    "run.configurations.get"
    "run.configurations.list"
    "run.executions.cancel"
    "run.executions.delete"
    "run.executions.get"
    "run.executions.list"
    "run.jobs.create"
    "run.jobs.delete"
    "run.jobs.get"
    "run.jobs.getIamPolicy"
    "run.jobs.list"
    "run.jobs.listEffectiveTags"
    "run.jobs.listTagBindings"
    "run.jobs.run"
    "run.jobs.runWithOverrides"
    "run.jobs.update"
    "run.locations.list"
    "run.operations.delete"
    "run.operations.get"
    "run.operations.list"
    "run.revisions.delete"
    "run.revisions.get"
    "run.revisions.list"
    "run.routes.get"
    "run.routes.list"
    "run.services.create"
    "run.services.delete"
    "run.services.get"
    "run.services.getIamPolicy"
    "run.services.list"
    "run.services.listEffectiveTags"
    "run.services.listTagBindings"
    "run.services.update"
)

# --- Create / update custom IAM role -----------------------------------
echo "Configuring IAM role: $role_name"
permissions_csv="$(concat_permissions "${permissions[@]}")"

role_id=$(gcloud iam roles describe "$role_name" \
    --project="$project_name" --format="value(name)" \
    --verbosity=none --quiet 2>/dev/null || true)

if [ -z "$role_id" ]; then
    echo "  Creating role $role_name ..."
    gcloud iam roles create "$role_name" \
        --description="PipeOps role — provisioning and cluster management" \
        --permissions="$permissions_csv" \
        --project="$project_name" --quiet
    role_id=$(gcloud iam roles describe "$role_name" \
        --project="$project_name" --format="value(name)" \
        --verbosity=none --quiet)
else
    echo "  Updating existing role $role_name ..."
    gcloud iam roles update "$role_name" \
        --permissions="$permissions_csv" \
        --project="$project_name" --quiet
fi
echo "  Role ready: $role_id"

# --- Create service account --------------------------------------------
service_account_email="${service_account_name}@${project_name}.iam.gserviceaccount.com"

echo "Configuring service account: $service_account_name"
if gcloud iam service-accounts describe "$service_account_email" \
    --project="$project_name" --verbosity=none &>/dev/null; then
    echo "  Service account already exists, skipping creation."
else
    echo "  Creating service account ..."
    gcloud iam service-accounts create "$service_account_name" \
        --display-name="$service_account_name" \
        --project="$project_name" --quiet
fi

# --- Bind role to service account --------------------------------------
echo "Binding role to service account ..."
gcloud projects add-iam-policy-binding "$project_name" \
    --member="serviceAccount:$service_account_email" \
    --role="$role_id" \
    --condition=None \
    --quiet >/dev/null
echo "  Role binding applied."

# --- Generate key ------------------------------------------------------
key_file="key.json"
echo "Generating service account key ..."
gcloud iam service-accounts keys create "$key_file" \
    --iam-account="$service_account_email" --quiet

echo ""
echo "========================================================"
echo "  Setup complete!"
echo "========================================================"
echo "  Project:          $project_name"
echo "  Service account:  $service_account_email"
echo "  Role:             $role_id"
echo "  Key file:         $key_file"
echo ""
echo "  Upload the contents of $key_file to PipeOps."
echo ""
echo "  ⚠  Store the key securely and delete the local copy"
echo "     after uploading: rm $key_file"
echo "========================================================"
